name: Atomic-design-ci
on:
  push:
    paths-ignore:
      - .github/workflows/*
  workflow_dispatch:
jobs:
  cache-node_modules:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cacheStep
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cacheStep.outputs.cache-hit != 'true'
        run: npm ci
  lint:
    needs: [cache-node_modules]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Install dependencies
        if: steps.cacheStep.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run lint
        run: npm run lint  
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Install dependencies
        if: steps.cacheStep.outputs.cache-hit != 'true'
        run: npm ci
