name: Atomic-design-ci
on:
  push:
    paths-ignore:
      - .github/workflows/*
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci