name: Atomic-design-cd
on:
  pull_request:
    paths-ignore:
      - .github/workflows/*
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to gh-pages
        run: npm run deploy
  
